In [1]:
import tensorflow as tf

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
model = tf.keras.models.load_model("saved_model/2021-08-23-v3-model")

In [3]:
import main

In [4]:
b = main.Board()

In [5]:
b.randomize(30)

In [6]:
b.pretty_print()

++○+++○++++++++++++
++++++++++○++++○○++
++++●++++○++++++++○
○+++++○++++++++++++
+++++++++++++++++++
+++++++○+++++++++++
++○+○++○+++++++++++
++++++○++++++++++++
+++++++++++++++○+++
+++++++++++++++++++
+○++○++++++++++++++
++++○+++++++○++++++
+++++++++○+++++++++
+++○+++++○○+++++○++
++++++++++++○+++○+○



In [7]:
array = b.get_flipped_3d_array()

In [8]:
array

array([[[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
    

In [9]:
import numpy as np

In [10]:
single = np.array([array,])

In [11]:
model.predict(single)

array([[0.7987658]], dtype=float32)

In [12]:
%%timeit
model.predict(single)

27.4 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


25500 microseconds

Now make a list of 10000 random boards

In [13]:
array_list = []
for i in range(10000):
    b.randomize(30)
    array_list.append(b.get_flipped_3d_array())

In [14]:
array_list[0]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
    

In [15]:
array_list[1]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
    

In [16]:
long_input = np.array(array_list)

In [17]:
%%timeit
model.predict(long_input)

1.02 s ± 16.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


121 microseconds

Hmm, so it takes 1.21 sec to do 10000. 
So the effective speed is 0.1210 millisecs

This is ~250 times faster than the 25 millisecs to do one board

In [18]:
%%timeit
model(single)

2.08 ms ± 59.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


2260 microseconds

In [19]:
shorter_input = long_input[:100]

In [20]:
%%timeit
model.predict(shorter_input)

38.4 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


440 microseconds

Hmm. So if I just use `model(single)`, that's a 10-fold improvement over `model.predict(single)`

But still 20 times slower than fully parallel

In [21]:
medium_input = long_input[:1000]

In [22]:
%%timeit
model.predict(medium_input)

132 ms ± 3.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


152 microseconds

What if I batch 50 at a time?

In [23]:
fifty_input = long_input[:50]

In [24]:
%%timeit
model.predict(fifty_input)

29.9 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


668 microseconds

In [25]:
%%timeit
model(fifty_input)

6.72 ms ± 30.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%%timeit
model(medium_input)

80.3 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%%timeit
model(long_input)

667 ms ± 12.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
%%timeit
model.predict(long_input)

974 ms ± 26.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
%%timeit
model(long_input)

660 ms ± 7.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%%timeit
model.predict(long_input)

975 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
long_input

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [1., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [1., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        ...,

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [1., 0.]],

        [[1., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         ...,
   

In [32]:
0.0 in (0,1)

True

In [34]:
moves = b.get_all_nearby_moves()

In [36]:
moves

{'A1': <main.Board at 0x17d017400>,
 'A2': <main.Board at 0x17d017d00>,
 'A4': <main.Board at 0x17d017220>,
 'A5': <main.Board at 0x17d017e50>,
 'B1': <main.Board at 0x17d0172e0>,
 'B2': <main.Board at 0x17d1ee5b0>,
 'B3': <main.Board at 0x17d1ee1c0>,
 'B4': <main.Board at 0x17d1ee880>,
 'C1': <main.Board at 0x17d0171f0>,
 'C2': <main.Board at 0x17d1ee520>,
 'C3': <main.Board at 0x17d1ee8e0>,
 'C4': <main.Board at 0x17d1ee8b0>,
 'C5': <main.Board at 0x17d1ee3a0>,
 'A12': <main.Board at 0x17d017430>,
 'A13': <main.Board at 0x17d1eef70>,
 'A15': <main.Board at 0x17d1eedf0>,
 'A16': <main.Board at 0x17d1eefd0>,
 'B12': <main.Board at 0x17d1eeeb0>,
 'B14': <main.Board at 0x17d1eef10>,
 'B15': <main.Board at 0x17d1eeaf0>,
 'B16': <main.Board at 0x17d1eec40>,
 'C12': <main.Board at 0x17d1eed90>,
 'C13': <main.Board at 0x17d1eecd0>,
 'C14': <main.Board at 0x17d1eeac0>,
 'C15': <main.Board at 0x17d1eebe0>,
 'A6': <main.Board at 0x17d017280>,
 'A7': <main.Board at 0x17d1eeb20>,
 'B6': <main.Boa